version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
  jenkins:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - db
